name: google_secret_manager
description: This package provides an API for accessing Google Secret Manager using Dart. This package is useful for developers who want to securely store and retrieve secrets.
version: 1.0.5
repository: https://github.com/jopmiddelkamp/dart_google_secret_manager

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  googleapis: ^10.1.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
